"""Added federation table

Revision ID: a1b2c3d4e5f6
Revises: 298430e7849d
Create Date: 2025-01-24 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '298430e7849d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ca_cert_path', sa.String(length=512), nullable=True),
    sa.Column('client_cert_path', sa.String(length=512), nullable=True),
    sa.Column('client_key_path', sa.String(length=512), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('push_data_types', sa.TEXT(), nullable=False),
    sa.Column('connection_status', sa.String(length=50), nullable=False),
    sa.Column('last_connected', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now()),
    sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now(), onupdate=func.now()),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('federations')
    # ### end Alembic commands ###
