"""Add transport_protocol to federation_servers

Revision ID: b1c2d3e4f5a6
Revises: a1b2c3d4e5f6
Create Date: 2025-11-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c2d3e4f5a6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add transport_protocol column to federation_servers table
    op.add_column('federation_servers',
        sa.Column('transport_protocol', sa.String(length=20), nullable=False, server_default='tcp')
    )
    # Note: Skipping alter_column to drop default - SQLite doesn't support this
    # The server_default is kept in the schema
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('federation_servers', 'transport_protocol')
    # ### end Alembic commands ###
